language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi

script:
  - make debug
  - make clean
  - make

branches:
  except:
    - /^\d+-/
